let emojis_list = [
	" 'ʘ‿ʘ' "; 
  " '( ͡° ͜ʖ ͡°)' " ;
  " 'ಠ_ಠ' "; 
	" '(╯°□°）╯︵ ┻━┻ ' ";
	" '┬─┬﻿ ノ( ゜-゜ノ)' "; 
	" '┬─┬⃰͡ (ᵔᵕᵔ͜ )' "; 
	" '┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻ '";
	" 'ლ(｀ー´ლ) '";
	" 'ʕ•ᴥ•ʔ '";
	" 'ʕᵔᴥᵔʔ '";
	" '(｡◕‿◕｡) '";
	" '（　ﾟДﾟ） '";
	" '¯\\_(ツ)_/¯' ";
	" '¯\\(°_o)/¯' ";
	" '(`･ω･´)' " ; 
	" '(╬ ಠ益ಠ)' ";
	" '☜(⌒▽⌒)☞' ";
	" 'ε=ε=ε=┌(;*´Д`)ﾉ' ";
	" 'ヽ(´▽`)/' " ; 
	" 'ヽ(´ー｀)ノ' ";
	" 'ᵒᴥᵒ#' ";
	" 'V●ᴥ●V' ";
	" 'ฅ^•ﻌ•^ฅ' ";
	" '（ ^_^）o自自o（^_^ ）' ";
	" 'ಠ‿ಠ' ";
	" '( ͡° ͜ʖ ͡°)' ";
	" 'ಥ_ಥ' ";
	" 'ಥ﹏ಥ' ";
	" '٩◔̯◔۶' ";
	" 'ᕙ(⇀‸↼‶)ᕗ' ";
	" 'ᕦ(ò_óˇ)ᕤ' ";
	" '⊂(◉‿◉)つ' ";
	" 'q(❂‿❂)p' ";
	" '⊙﹏⊙' ";
	" '¯\\_(⊙︿⊙)_/¯' ";
	" '°‿‿°' ";
	" '¿ⓧ_ⓧﮌ' ";
	" '(⊙.☉)7' ";
	" '(´･_･`)' ";
	" 'щ（ﾟДﾟщ）' ";
	" '٩(͡๏_๏)۶' ";
	" 'ఠ_ఠ' ";
	" 'ᕕ( ᐛ )ᕗ' ";
	" '(⊙_◎)' ";
	" 'ミ●﹏☉ミ' ";
	" '༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽' ";
	" 'ヽ༼ ಠ益ಠ ༽ﾉ' ";
	" 't(-_-t)' ";
	" '(ಥ⌣ಥ)' ";
	" '(づ￣ ³￣)づ' ";
	" '(づ｡◕‿‿◕｡)づ' ";
	" '｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡' ";
	" '༼ ༎ຶ ෴ ༎ຶ༽' ";
	" '┌(ㆆ㉨ㆆ)ʃ' ";
	" '눈_눈' ";
	" '( ఠൠఠ )ﾉ' ";
	" '乁( ◔ ౪◔)「      ┑(￣Д ￣)┍' ";
	" '(๑•́ ₃ •̀๑) ' ";
	" '⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾' ";
	" '◔_◔' ";
	" '♥‿♥' ";
	" 'ԅ(≖‿≖ԅ)' ";
	" '( ˘ ³˘)♥ ' ";
	" '( ˇ෴ˇ )' ";
	" 'ヾ(-_- )ゞ ' ";
	" '♪♪ ヽ(ˇ∀ˇ )ゞ' ";
	" 'ヾ(´〇`)ﾉ♪♪♪' ";
	" 'ʕ •́؈•̀ ₎' ";
	" 'ლ(•́•́ლ)' ";
	" '{•̃_•̃}' ";
	" '(ᵔᴥᵔ)' ";
	" '(Ծ‸ Ծ)' ";
	" '(•̀ᴗ•́)و ̑̑' ";
	" '[¬º-°]¬' ";
	" '(☞ﾟヮﾟ)☞' ";
	] 

let languages = [
    "Automatic";
    "Afrikaans";
    "Albanian";
    "Amharic";
    "Arabic";
    "Armenian";
    "Azerbaijani";
    "Basque";
    "Belarusian";
    "Bengali";
    "Bosnian";
    "Bulgarian";
    "Catalan";
    "Cebuano";
    "Chichewa";
    "Chinese Simplified";
    "Chinese Traditional";
    "Corsican";
    "Croatian";
    "Czech";
    "Danish";
    "Dutch";
    "English";
    "Esperanto";
    "Estonian";
    "Filipino";
    "Finnish";
    "French";
    "Frisian";
    "Galician";
    "Georgian";
    "German";
    "Greek";
    "Gujarati";
    "Haitian Creole";
    "Hausa";
    "Hawaiian";
    "Hebrew";
    "Hindi";
    "Hmong";
    "Hungarian";
    "Icelandic";
    "Igbo";
    "Indonesian";
    "Irish";
    "Italian";
    "Japanese";
    "Javanese";
    "Kannada";
    "Kazakh";
    "Khmer";
    "Korean";
    "Kurdish (Kurmanji)";
    "Kyrgyz";
    "Lao";
    "Latin";
    "Latvian";
    "Lithuanian";
    "Luxembourgish";
    "Macedonian";
    "Malagasy";
    "Malay";
    "Malayalam";
    "Maltese";
    "Maori";
    "Marathi";
    "Mongolian";
    "Myanmar (Burmese)";
    "Nepali";
    "Norwegian";
    "Pashto";
    "Persian";
    "Polish";
    "Portuguese";
    "Punjabi";
    "Romanian";
    "Russian";
    "Samoan";
    "Scots Gaelic";
    "Serbian";
    "Sesotho";
    "Shona";
    "Sindhi";
    "Sinhala";
    "Slovak";
    "Slovenian";
    "Somali";
    "Spanish";
    "Sundanese";
    "Swahili";
    "Swedish";
    "Tajik";
    "Tamil";
    "Telugu";
    "Thai";
    "Turkish";
    "Ukrainian";
    "Urdu";
    "Uzbek";
    "Vietnamese";
    "Welsh";
    "Xhosa";
    "Yiddish";
    "Yoruba";
    "Zulu";
    ]

let lang_to_identifier lang_str =
  begin match lang_str with 
  | "Automatic" -> "auto"; 
  | "Afrikaans" -> "af";
  | "Albanian" -> "sq";
  | "Amharic" -> "am";
  | "Arabic" -> "ar";
  | "Armenian" -> "hy";
  | "Azerbaijani" -> "az";
  | "Basque" -> "eu";
  | "Belarusian" -> "be";
  | "Bengali" -> "bn";
  | "Bosnian" -> "bs";
  | "Bulgarian" -> "bg";
  | "Catalan" -> "ca";
  | "Cebuano" -> "ceb";
  | "Chichewa" -> "ny";
  | "Chinese Simplified" -> "zh-cn";
  | "Chinese Traditional" -> "zh-tw";
  | "Corsican" -> "co";
  | "Croatian" -> "hr";
  | "Czech" -> "cs";
  | "Danish" -> "da";
  | "Dutch" -> "dl";
  | "English" -> "en";
  | "Esperanto" -> "eo";
  | "Estonian" -> "et";
  | "Filipino" -> "tl";
  | "Finnish" -> "fi";
  | "French" -> "fr";
  | "Frisian" -> "fy";
  | "Galician" -> "gl";
  | "Georgian" -> "ka";
  | "German" -> "de";
  | "Greek" -> "el";
  | "Gujarati" -> "gu";
  | "Haitian Creole" -> "ht";
  | "Hausa" -> "ha";
  | "Hawaiian" -> "haw";
  | "Hebrew" -> "iw";
  | "Hindi" -> "hi";
  | "Hmong" -> "hmn";
  | "Hungarian" -> "hu";
  | "Icelandic" -> "is";
  | "Igbo" -> "ig";
  | "Indonesian" -> "id";
  | "Irish" -> "ga";
  | "Italian" -> "it";
  | "Japanese" -> "ja";
  | "Javanese" -> "jw";
  | "Kannada" -> "kn";
  | "Kazakh" -> "kk";
  | "Khmer" -> "km";
  | "Korean" -> "ko";
  | "Kurdish (Kurmanji)" -> "ku";
  | "Kyrgyz" -> "ky";
  | "Lao" -> "lo";
  | "Latin" -> "la";
  | "Latvian" -> "lv";
  | "Lithuanian" -> "lt";
  | "Luxembourgish" -> "lb";
  | "Macedonian" -> "mk";
  | "Malagasy" -> "mg";
  | "Malay" -> "ms";
  | "Malayalam" -> "ml";
  | "Maltese" -> "mt";
  | "Maori" -> "mi";
  | "Marathi" -> "mr";
  | "Mongolian" -> "mn";
  | "Myanmar (Burmese)" -> "my";
  | "Nepali" -> "ne";
  | "Norwegian" -> "no";
  | "Pashto" -> "ps";
  | "Persian" -> "fa";
  | "Polish" -> "pl";
  | "Portuguese" -> "pt";
  | "Punjabi" -> "ma";
  | "Romanian" -> "ro";
  | "Russian" -> "ru";
  | "Samoan" -> "sm";
  | "Scots Gaelic" -> "gd";
  | "Serbian" -> "sr";
  | "Sesotho" -> "st";
  | "Shona" -> "sn";
  | "Sindhi" -> "sd";
  | "Sinhala" -> "si";
  | "Slovak" -> "sk";
  | "Slovenian" -> "sl";
  | "Somali" -> "so";
  | "Spanish" -> "es";
  | "Sundanese" -> "su";
  | "Swahili" -> "sw";
  | "Swedish" -> "sv";
  | "Tajik" -> "tg";
  | "Tamil" -> "ta";
  | "Telugu" -> "te";
  | "Thai" -> "th";
  | "Turkish" -> "tr";
  | "Ukrainian" -> "uk";
  | "Urdu" -> "ur";
  | "Uzbek" -> "uz";
  | "Vietnamese" -> "vi";
  | "Welsh" -> "cy";
  | "Xhosa" -> "xh";
  | "Yiddish" -> "yi";
  | "Yoruba" -> "yo";
  | "Zulu" -> "zu";
  | _ -> "auto";
  end
